String simpleCsdText = "<Cabbage>\n"
                       "form size(400, 200), caption(\"AndroidSynth\"), pluginID(\"plu1\")\n"
                       "keyboard bounds(12, 10, 360, 143)\n"
                       "\n"
                       "</Cabbage>\n"
                       "<CsoundSynthesizer>\n"
                       "<CsOptions>\n"
                       "-n -d -+rtmidi=NULL -M0 --midi-key-cps=4 --midi-velocity-amp=5\n"
                       "</CsOptions>\n"
                       "<CsInstruments>\n"
                       "sr = 44100\n"
                       "ksmps = 64\n"
                       "nchnls = 2\n"
                       "0dbfs=1\n"
                       "\n"
                       "instr 1\n"
                       "a1 oscili p5, p4, 1\n"
                       "outs a1, a1\n"
                       "endin\n"
                       "\n"
                       "</CsInstruments>  \n"
                       "<CsScore>\n"
                       "f1 0 1024 10 1\n"
                       "f0 3600\n"
                       "</CsScore>\n"
                       "</CsoundSynthesizer>";