#!/bin/bash  

if [ $1 = "plugins" ]; then
echo "Building Cabbage plugin libraries! "
make -f MakefilePluginEffect clean CONFIG=Release
make -f MakefilePluginEffect -j8 CONFIG=Release
make -f MakefilePluginSynth clean CONFIG=Release
make -f MakefilePluginSynth -j8 CONFIG=Release
elif [ $1 = "standalone" ]; then
echo "Building Cabbage standalone! "
make -f MakefileStandalone clean CONFIG=Release
make -f MakefileStandalone -j8 CONFIG=Release
else
echo "Building Cabbage! "
make -f MakefileStandalone clean CONFIG=Release
make -f MakefileStandalone -j8 CONFIG=Release
make -f MakefilePluginEffect clean CONFIG=Release
make -f MakefilePluginEffect -j8 CONFIG=Release
make -f MakefilePluginSynth clean CONFIG=Release
make -f MakefilePluginSynth -j8 CONFIG=Release
rm -rf CabbageBuild
mkdir CabbageBuild
cp ./build/Cabbage CabbageBuild/Cabbage
cp cabbage.desktop CabbageBuild/cabbage.desktop
cp ./build/CabbagePluginSynth.so CabbageBuild/CabbagePluginSynth.so
cp ./build/CabbagePluginEffect.so CabbageBuild/CabbagePluginEffect.so
cp -rf ../../Docs/ CabbageBuild/Docs
cp ../../Images/logo_cabbage_black_no_text.png CabbageBuild/logo.png
sed "s@CURRENTDIR@$(pwd)@" dummy.desktop > CabbageBuild/cabbage.desktop
cp CabbageBuild/cabbage.desktop ~/.local/share/applications/
fi
