/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "AudioFilePlaybackProcessor.h"
#include "AudioFilePlaybackEditor.h"


//==============================================================================
AudioFilePlaybackEditor::AudioFilePlaybackEditor (AudioFilePlaybackProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter), startStop("StartStop"), loadFile("LoadFile")
{
    AudioFormatManager formatManager;
    formatManager.registerBasicFormats();  
	waveformDisplay = new WaveformDisplay(formatManager, *getFilter()->bufferingAudioFileSource, getFilter()->sourceSampleRate);
	setOpaque(false);
	startStop.addListener(this);
	addAndMakeVisible(&startStop);
	loadFile.addListener(this);
	addAndMakeVisible(&loadFile);

	viewport = new Viewport();
	waveformDisplay->setBounds(0, 0, 500, 200);
	viewport->setViewedComponent(waveformDisplay, false);
	viewport->setScrollBarsShown(true, true);
	addAndMakeVisible(viewport);
    setSize (400, 300);

	waveformDisplay->setFile(File("/home/rory/Documents/BeesInMarch4.wav"));
	waveformDisplay->setZoomFactor(1);

}

AudioFilePlaybackEditor::~AudioFilePlaybackEditor()
{
}

void AudioFilePlaybackEditor::buttonClicked(Button *button)
{
	if(button->getName()=="StartStop")
	{
		if(!getFilter()->isSourcePlaying)
			waveformDisplay->startTimer(10);
		else
			waveformDisplay->stopTimer();

		getFilter()->isSourcePlaying=!getFilter()->isSourcePlaying;
	}
	else if(button->getName()=="LoadFile")
	{
	    FileChooser fc ("Open file");

	    if (fc.browseForFileToOpen())
	        waveformDisplay->setFile(fc.getResult());		
	}
			

}
//==============================================================================
void AudioFilePlaybackEditor::resized()
{
	viewport->setBounds(0, 0, 400, 200);
	startStop.setBounds(0, 220, 60, 40);
	loadFile.setBounds(70, 220, 60, 40);
}
//==============================================================================
void AudioFilePlaybackEditor::paint (Graphics& g)
{
	g.fillAll(Colours::black);
}
