/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINWRAPPEREDITOR_H_INCLUDED
#define PLUGINWRAPPEREDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginWrapperProcessor.h"


//==============================================================================
/**
*/
class PluginWrapperEditor  : public AudioProcessorEditor,
							 public Timer
{
public:
    PluginWrapperEditor (PluginWrapperProcessor&);
    ~PluginWrapperEditor();

    //==============================================================================
	PluginWrapperProcessor* getFilter() const
    {
        return static_cast <PluginWrapperProcessor*> (getAudioProcessor());
    }

	void timerCallback();
private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    PluginWrapperProcessor& processor;
    AudioProcessorEditor* vstEditor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (PluginWrapperEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
